import clsx from "clsx";
import Head from "next/head";
import React from "react";
import { Rubik } from "next/font/google";
import type { GetServerSideProps, GetServerSidePropsContext } from "next";

const font = Rubik({
  subsets: ["latin-ext"],
});

export const getServerSideProps: GetServerSideProps = async () => {
  // fetch todos from json placeholder
  const uniqueId = new Date().getTime().toString();
  const res = await fetch(
    "https://child-next-app-2.vercel.app/api/createToken",
    {
      method: "POST",
      credentials: "include",
      body: JSON.stringify({ key: uniqueId }),
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    },
  );
  //   console.log(JSON.stringify({ key: uniqueId }));
  return {
    redirect: {
      destination: `https://child-next-app-2.vercel.app/token/${uniqueId}`,
      permanent: true,
    },
  };
};

export default function Proxy() {
  return (
    <React.Fragment>
      <Head>
        <title>Iframe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <div className="grid grow place-items-center bg-white">
          <span className="text-gray-400">Loading...</span>
        </div>
      </main>
    </React.Fragment>
  );
}
