import clsx from "clsx";
import { Rubik } from "next/font/google";
import Head from "next/head";
import React from "react";
import { GetServerSideProps } from "next";

const font = Rubik({
  subsets: ["latin-ext"],
});

//getServerSideProps with Typescript
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  ctx.res.setHeader(
    "Set-Cookie",
    "name=Mike; domain:localhost:3001; SameSite=None; Secure",
  );
  return {
    props: {},
  };
};

export default function Iframe() {
  return (
    <React.Fragment>
      <>
        <Head>
          <title>Iframe</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={clsx(font.className, "flex min-h-screen flex-col")}>
          <nav className="bg-gradient-to-r from-sky-400 via-sky-400 to-sky-700">
            <div className="container mx-auto max-w-screen-xl px-4 py-4">
              <span className="text-4xl text-white">Parent App</span>
            </div>
          </nav>
          <div className="grow bg-gradient-to-b from-sky-100 to-sky-50">
            <div className="container mx-auto max-w-screen-xl px-4 py-4">
              <div className="mt-6 text-2xl font-bold text-gray-800">
                Iframe
              </div>
              <div className="mt-2 flex h-[60dvh] flex-col overflow-hidden rounded-lg bg-white">
                <iframe
                  src="http://localhost:3001"
                  className="h-full w-full grow"
                ></iframe>
              </div>
            </div>
          </div>
        </main>
      </>
    </React.Fragment>
  );
}
