import clsx from "clsx";
import { Rubik } from "next/font/google";
import Head from "next/head";
import React, { useCallback, useEffect } from "react";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Iframe() {
  const [, setLoading] = React.useState<boolean>(false);
  const [showIframe, setShowIframe] = React.useState<boolean>(false);

  const handleCitiLogin = useCallback(() => {
    setLoading(true);
    fetch("https://child-next-app.vercel.app/api/token", {
      method: "POST",
      credentials: "include",
      // headers: {
      //   "Access-Control-Allow-Origin": "https://child-next-app.vercel.app",
      //   "Access-Control-Allow-Credentials": "true",
      // },
    })
      .then((res) => res.json())
      .then(() => {
        setLoading(false);
        setShowIframe(false);
        setTimeout(() => {
          setShowIframe(true);
        }, 1000);
      })
      .catch(() => {
        setLoading(false);
      });
  }, []);

  useEffect(() => {
    handleCitiLogin();
  }, []);

  return (
    <React.Fragment>
      <Head>
        <title>Iframe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <nav className="bg-gradient-to-r from-gray-700 via-gray-700 to-gray-800">
          <div className="container mx-auto max-w-screen-xl px-4 py-4">
            <span className="text-4xl text-white">EJ Frame</span>
          </div>
        </nav>
        <div className="grow bg-gray-100">
          <div className="container mx-auto max-w-screen-xl px-4 py-4">
            <div className="mt-2 flex h-[90dvh] flex-col overflow-hidden rounded-lg bg-white shadow">
              {showIframe && (
                <iframe
                  src="https://child-next-app.vercel.app"
                  className="h-full w-full grow"
                  sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-modals allow-top-navigation"
                ></iframe>
              )}
            </div>
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
